services:
  - type: web
    name: sincrofubb-backend
    env: python
    plan: free
    buildCommand: pip install -r sincroFubb/requirements.txt
    startCommand: python sincroFubb/resultados.py
    envVars:
      - key: PORT
        value: 10000
